CREATE TABLE DIM_CLIENTE(
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    PART_CONTA_CONJUNTA DECIMAL(5,2),
    NOME VARCHAR(200) NOT NULL,
    GERENTE VARHCAR(100) NOT NULL,
    ENDERECO VARCHAR(255),
    RENDA DECIMAL(18,2),
    PROFISSAO VARCHAR(200),
    SEGMENTO VARCHAR(200),
    CLASS_RISCO VARCHAR(20),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    CLASS_COMERCIAL VARCHAR(20),
    FLAG_ATUALIZACAO BOOLEAN NOT NULL
);

CREATE TABLE DIM_CONTA(
    ID_CONTA INT IDENTITY(1,1) PRIMARY KEY,
    ID_AGENCIA INT NOT NULL,
    NUMERO_CONTA VARCHAR(20) NOT NULL,
    TIPO_CONTA VARCHAR(100) NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    STATUS BOOLEAN NOT NULL
    CONSTRAINT FK_DIM_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES DIM_AGENCIA(ID_AGENCIA),
);

CREATE TABLE DIM_PRODUTO(
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_GERENTE(
    ID_GERENTE INT IDENTITY(1,1) PRIMARY KEY,
    ID_AGENCIA INT NOT NULL,
    NOME_GERENTE VARCHAR(100) NOT NULL,
    EQUIPE VARCHAR(100),
    REGIAO VARCHAR(100),
    DIRETORIA VARCHAR(100),
     CONSTRAINT FK_DIM_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES DIM_AGENCIA(ID_AGENCIA),
);

CREATE TABLE DIM_TEMPO(
    ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DATA DATE NOT NULL,
    ANO YEAR NULL,
    MES MONTH NOT NULL,
    DIA DAY NOT NULL,
    TRIMESTRE INT NOT NULL,
    SEMESTRE INT NOT NULL
);

CREATE TABLE DIM_CALENDARIO(
    ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DATA_TRANSACAO DATE NOT NULL,
    DATA_PROCESSAMENTO DATE NOT NULL,
    DATA_LIQUIDEZ DATE NOT NULL
);

CREATE TABLE DIM_INVESTIMENTO(
    INVESTIMENTO_ID INT IDENTITY(1,1) PRIMARY KEY,
    TPO_INVESTIMENTO VARCHAR(50) NOT NULL,
    DESCRICAO VARCHAR(100),
    TAXA DECIMAL(18,2),
    PRAZO DATE,
    LIQUIDEZ VARCHAR(50) NOT NULL,
    CLASS_RISCO VARCHAR(20) NOT NULL,
    INSTITUICAO VARCHAR(200)
);

CREATE TABLE DIM_CREDITO(
    ID_CREDITO INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_CREDITO VARCHAR(50) NOT NULL,
    SEGMENTO VARCHAR(100),
    CLASS_RISCO VARCHAR(20) NOT NULL,
    LIMITE_CREDITO DECIMAL(18,2) NOT NULL,
    TAXA_JUROS DECIMAL(18,2),
    PRAZO INT
);

CREATE TABLE DIM_AGENCIA(
    ID_AGENCIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_LOCALIZACAO INT NOT NULL,
    NOME_AGENCIA VARCHAR(50) NOT NULL
    CONSTRAINT FK_DIM_LOCALIZACAO FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_LOCALIZACAO(ID_LOCALIZACAO),
);

CREATE TABLE DIM_CANAL(
    ID_CANAL INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    TIPO_CANAL VARCHAR(100) NOT NULL
);

CREATE TABLE DIM_CARTAO(
    ID_CARTAO INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_CARTAO VARCHAR(100) NOT NULL,
    BANDEIRA VARCHAR(50),
    LIMITE_CREDITO DECIMAL(18,2) NOT NULL
);

CREATE TABLE DIM_LOCALIZACAO(
    ID_LOCALIZACAO INT IDENTITY(1,1) PRIMARY KEY,
    REGIAO VARCHAR(200) NOT NULL,
    ESTADO VARCHAR(200) NOT NULL,
    PAIS VARCHAR(200) NOT NULL,
    CIDADE VARCHAR(200) NOT NULL
);

/*CREATE TABLE DIM_TIPO_TRANSACAO(
    ID_TIPO_TRANSACAO INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO VARCHAR(100)
);*/

CREATE TABLE DIM_CONTRATO(
    ID_CONTRATO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    DATA_CONTRATACAO DATE,
    VALOR_CONTRATO DECIMAL(18,2),
    TAXA DECIMAL(18,2),
    PRAZO INT,
    QTD_PARCELAS INT,
    VENCIMENTO DATE,
    STATUS VARCHAR(50),
    ATRASOS VARCHAR(50),
    NEGOCIACOES VARCHAR(50),
    LIQUIDACAO_ANTECIPADA VARCHAR(100),
    REFINAMENTO VARCHAR(100),
    INADIMPLENCIA VARCHAR(100)
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO),

);


CREATE TABLE DIM_CAMPANHA(
    ID_CAMPANHA INT IDENTITY(1,1) PRIMARY KEY 
    NOME_CAMPANHA VARCHAR(100),
    TIPO_CAMPANHA VARCHAR(100) NOT NULL,
    DATA_INICIO DATE,
    DATA_FIM DATE
);



