CREATE TABLE DIM_CLIENTE(
    ID_CLIENTE INT IDENTITY(1,1) PRIMARY KEY,
    ID_CONTA INT,
    ID_CARTAO INT,
    ID_INVESTIMENTO INT,
    ID_EMPRESTIMO INT,
    PART_CONTA_CONJUNTA DECIMAL(5,2),
    NOME VARCHAR(200),
    ENDERECO VARCHAR(255),
    RENDA DECIMAL(18,2),
    PROFISSAO VARCHAR(200),
    SEGMENTO VARCHAR(200),
    CLASS_RISCO VARCHAR(20),
    CLASS_COMERCIAL VARCHAR(20),
    SALDO DECIMAL(18,2)
);

CREATE TABLE DIM_CONTA(
    ID_CONTA INT IDENTITY(1,1) PRIMARY KEY,
    ID_AGENCIA INT,
    NUMERO_CONTA VARCHAR(20),
    TIPO_CONTA VARCHAR(100),
    DATA_ABERTURA DATE,
    STATUS BOOLEAN
);

CREATE TABLE DIM_PRODUTO(
    ID_PRODUTO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100),
    CATEGORIA VARCHAR(100)
);

CREATE TABLE DIM_GERENTE(
    ID_GERENTE INT IDENTITY(1,1) PRIMARY KEY,
    ID_AGENCIA INT,
    NOME_GERENTE VARCHAR(100),
    EQUIPE VARCHAR(100),
    REGIAO VARCHAR(100),
    DIRETORIA VARCHAR(100),
    FOREIGN KEY (ID_AGENCIA) REFERENCES DIM_AGENCIA(ID_AGENCIA)
);

CREATE TABLE DIM_TEMPO(
    ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DATA DATE,
    ANO YEAR,
    MES MONTH,
    DIA DAY,
    TRIMESTRE VARCHAR(3),
    SEMESTRE VARCHAR(10)
);

CREATE TABLE DIM_CALENDARIO(
    ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DATA_TRANSACAO DATE,
    DATA_PROCESSAMENTO DATE,
    DATA_LIQUIDEZ DATE
);

CREATE TABLE DIM_INVESTIMENTO(
    INVESTIMENTO_ID INT IDENTITY(1,1) PRIMARY KEY,
    TPO_INVESTIMENTO VARCHAR(50),
    DESCRICAO VARCHAR(100),
    TAXA DECIMAL(18,2),
    PRAZO DATE,
    LIQUIDEZ DECIMAL(18,2),
    CLASS_RISCO VARCHAR(20),
    INSTITUICAO VARCHAR(200)
);

CREATE TABLE DIM_CREDITO(
    ID_CREDITO INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_CREDITO VARCHAR(50),
    SEGMENTO VARCHAR(100),
    CLASS_RISCO VARCHAR(20),
    LIMITE_CREDITO DECIMAL(18,2),
    TAXA_JUROS DECIMAL(18,2),
    PRAZO INT
);

CREATE TABLE DIM_AGENCIA(
    ID_AGENCIA INT IDENTITY(1,1) PRIMARY KEY,
    ID_LOCALIZACAO INT,
    NOME_AGENCIA VARCHAR(50)
);

CREATE TABLE DIM_CANAL(
    ID_CANAL INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO VARCHAR(100),
    TIPO_CANAL VARCHAR(100)
);

CREATE TABLE DIM_CARTAO(
    ID_CARTAO INT IDENTITY(1,1) PRIMARY KEY,
    TIPO_CARTAO VARCHAR(100),
    BANDEIRA VARCHAR(50),
    LIMITE_CREDITO DECIMAL(18,2)
);

CREATE TABLE DIM_LOCALIZACAO(
    ID_LOCALIZACAO INT IDENTITY(1,1) PRIMARY KEY,
    REGIAO VARCHAR(200),
    ESTADO VARCHAR(200),
    PAIS VARCHAR(200),
    CIDADE VARCHAR(200)
);

/*CREATE TABLE DIM_TIPO_TRANSACAO(
    ID_TIPO_TRANSACAO INT IDENTITY(1,1) PRIMARY KEY,
    DESCRICAO VARCHAR(100)
);*/

CREATE TABLE DIM_CONTRATO(
    ID_CONTRATO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_PAGAMENTO INT,
    ID_PRODUTO INT,
    DATA_CONTRATACAO DATE,
    VALOR_CONTRATO DECIMAL(18,2),
    TAXA DECIMAL(18,2),
    PRAZO INT,
    QTD_PARCELAS INT,
    VENCIMENTO DATE,
    STATUS VARCHAR(50),
    ATRASOS VARCHAR(50),
    NEGOCIACOES VARCHAR(50),
    LIQUIDACAO_ANTECIPADA VARCHAR(100),
    REFINAMENTO VARCHAR(100),
    INADIMPLENCIA VARCHAR(100)
);


CREATE TABLE DIM_CAMPANHA(
    ID_CAMPANHA INT IDENTITY(1,1) PRIMARY KEY 
    NOME_CAMPANHA VARCHAR(100),
    TIPO_CAMPANHA VARCHAR(100),
    DATA_INICIO DATE,
    DATA_FIM DATE
);



