CREATE TABLE FATO_TRANSACAO (
    ID_FATO_TRANSACAO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_CONTA INT,
    ID_CONTA_ORIGEM INT,
    ID_CONTA_DESTINO INT,
    ID_CANAL INT,
    ID_CALENDARIO INT,
    --ID_TIPO_TRANSACAO INT,
    TIPO_TRANSACAO VARCHAR(100),
    ID_LOCALIZACAO INT,
    ID_TEMPO INT,
    ID_CREDITO INT,
    DATA DATE,
    HORARIO DATETIME,
    VALOR_TRANSACAO DECIMAL(18,2),
    MOEDA DECIMAL(18,2),
    STATUS VARCHAR(50),
    SALDO_TRANSACAO DECIMAL(18,2),
    DISPOSITIVO VARCHAR(200),
    TICKET_MEDIO DECIMAL(18,2),
     CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
     CONSTRAINT FK_DIM_CONTA FOREIGN KEY (ID_CONTA) REFERENCES DIM_CONTA(ID_CONTA),
     CONSTRAINT FK_DIM_CANAL FOREIGN KEY (ID_CANAL) REFERENCES DIM_CANAL(ID_CANAL),
     CONSTRAINT FK_DIM_CALENDARIO FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
     CONSTRAINT FK_DIM_TIPO_TRANSACAO --FOREIGN KEY (ID_TIPO_TRANSACAO) REFERENCES DIM_TIPO_TRANSACAO(ID_TIPO_TRANSACAO),
     CONSTRAINT FK_DIM_LOCALIZACAO FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_LOCALIZACAO(ID_LOCALIZACAO),
     CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
     CONSTRAINT FK_DIM_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES DIM_CREDITO(ID_CREDITO)
);

CREATE TABLE FATO_INVESTIMENTO (
    ID_INVESTIMENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_PRODUTO INT, 
    ID_TEMPO INT,
    INVESTIMENTO_ID INT,
    VALOR_APLICADO DECIMAL(18,2),
    RESGASTES DECIMAL(18,2),
    SALDO DECIMAL(18,2),
    PATRIMONIO DECIMAL(18,2),
    PRODUTO VARCHAR(50),
    EMISSOR VARCHAR(50),
    CARTEIRA VARCHAR(50),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
    CONSTRAINT FK_DIM_INVESTIMENTO FOREIGN KEY (INVESTIMENTO_ID) REFERENCES DIM_INVESTIMENTO(INVESTIMENTO_ID),
);

CREATE TABLE FATO_RISCO_ANTIFRAUDE(
    ID_ANTIFRAUDE INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_TEMPO INT,
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
);

CREATE TABLE FATO_ABERTURA_CONTA(
    ID_CLIENTE INT,
    ID_TEMPO INT,
    ID_AGENCIA INT,
    ID_CONTA INT,
    ID_GERENTE INT
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
    CONSTRAINT FK_DIM_AGENCIA FOREIGN KEY (ID_AGENCIA) REFERENCES DIM_AGENCIA(ID_AGENCIA),
    CONSTRAINT FK_DIM_CONTA FOREIGN KEY (ID_CONTA) REFERENCES DIM_CONTA(ID_CONTA),
    CONSTRAINT FK_DIM_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES DIM_GERENTE(ID_GERENTE)
);

CREATE TABLE FATO_EMPRESTIMO(
    ID_EMPRESTIMO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    ID_CREDITO INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    ID_GERENTE INT NOT NULL,
    NUM_CONTRATO INT NOT NULL,
    VALOR_CONTRATADO DECIMAL(18,2),
    SALDO_DEVEDOR DECIMAL(18,2),
    JUROS DECIMAL(18,2),
    PARCELAS DECIMAL(18,2),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES DIM_CREDITO(ID_CREDITO),
    CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_DIM_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES DIM_GERENTE(ID_GERENTE)
);

CREATE TABLE FATO_SALDO(
    ID_SALDO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_CONTA INT,
    ID_CREDITO INT,
    ID_PRODUTO INT,
    ID_TEMPO INT,
    DATA DATE,
    SALDO_DISPONIVEL DECIMAL(18,2),
    SALDO_MEDIO DECIMAL(18,2),
    SALDO_BLOQUEADO DECIMAL(18,2),
    SALDO_AGENCIA DECIMAL(18,2),
    SALDO_SEGMENTO DECIMAL(18,2),
    LIMITE_CREDITO DECIMAL(18,2),
    TIPO_SALDO VARCHAR(50),
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_CONTA FOREIGN KEY (ID_CONTA) REFERENCES DIM_CONTA(ID_CONTA),
    CONSTRAINT FK_DIM_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES DIM_CREDITO(ID_CREDITO),
    CONSTRAINT FK_DIM_PRODUTO FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO),
    CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO)

);

CREATE TABLE FATO_COMPRA(
    ID_COMPA INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    ID_CONTRATO INT,
    ID_CARTAO INT,
    ID_LOCALIZACAO INT,
    ID_TEMPO INT,
    ESTABELECIMENTO VARCHAR(100),
    MCC VARCHAR(100),
    VALOR DECIMAL(18,2),
    MOEDA DECIMAL(18,2),
    DATA DATE,
    AUTORIZACAO BOOLEAN,
    QTD_PARCELAS INT,
    FECHAMENTO_FATURA BOOLEAN,
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES DIM_CONTRATO(ID_CONTRATO),
    CONSTRAINT FK_DIM_CARTAO FOREIGN KEY (ID_CARTAO) REFERENCES DIM_CARTAO(ID_CARTAO),
    CONSTRAINT FK_DIM_LOCALIZACAO FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_LOCALIZACAO(ID_LOCALIZACAO),
    CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO)
);

CREATE TABLE FATO_EVENTO(
    ID_EVENTO INT IDENTITY(1,1) PRIMARY KEY,
    ID_CLIENTE INT,
    TIPO_EVENTO VARCHAR(100),
    DATA_EVENTO DATE
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE)
);

CREATE TABLE FATO_ELEGIBILIDADE(
    ID_CLIENTE INT,
    ID_CAMPANHA INT,
    ELEGIVEL BOOLEAN
    CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    CONSTRAINT FK_DIM_CAMPANHA FOREIGN KEY (ID_CAMPANHA) REFERENCES DIM_CLIENTE(ID_CAMPANHA)
);