CREATE TABLE BRIGDE_CLIENTE_CONTA(
    ID_CLIENTE INT,
    ID_CONTA INT,
    PERC_PARTICIPACAO DECIMAL(5,2),
    DATA_INICIO DATE,
    DATA_FIM DATE,
    PRIMARY KEY(ID_CLIENTE,ID_CONTA)
    FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_CONTA) REFERENCES DIM_CONTA(ID_CONTA),
);

CREATE TABLE BRIGDE_CLIENTE_GERENTE(
    ID_CLIENTE INT,
    ID_GERENTE INT,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    PRIMARY KEY(ID_CLIENTE,ID_GERENTE),
    FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_GERENTE) REFERENCES DIM_GERENTE(ID_GERENTE),
);

CREATE TABLE BRIGDE_CLIENTE_PRODUTO(
    ID_CLIENTE INT,
    ID_PRODUTO INT,
    DATA_INICIO DATE,
    DATA_FIM DATE,
    PRIMARY KEY(ID_CLIENTE,ID_PRODUTO),
    FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_PRODUTO) REFERENCES DIM_PRODUTO(ID_PRODUTO),
);
