1 - consulta 

SELECT 20 TOP,
        C.NOME AS CLIENTE,
        C.SEGMENTO,
        COUNT(T.VALOR) AS QTD_TRANSACOES,
        SUM(T.VALOR) AS VALOR_TOTAL,
        AVG(T.VALOR) AS TICKET_MEDIO
FROM FATO_TRANSACAO T 
JOIN DIM_CLIENTE C 
ON T.ID_CLIENTE = C.ID_CLIENTE
JOIN DIM_CALENDARIO CAL 
ON T.ID_TEMPO = CAL.ID_ID_TEMPO
WHERE CAL.DATA_TRANSACAO >= DATEDIFF(DAY,-90,GETDATE())
GROUP BY C.NOME,C.SEGMENTO
ORDER BY VALOR_TOTAL DESC;

2- CONSULTA 

SELECT C.NOME AS CLIENTE,
AVG(C.SALDO) AS SALDO_MEDIO
FROM FATO_TRANSACAO T
JOIN DIM_CLIENTE C
ON T.ID_CLIENTE = C.ID_CLIENTE
JOIN DIM_TIPO_TRANSACAO TT 
ON T.ID_TIPO_TRANSACAO = TT.ID_TIPO_TRANSACAO
JOIN CAL.DIM_CALENDARIO 
ON CAL.ID_TEMPO = T.ID_TEMPO
JOIN DIM_TEMPO TEM 
ON TEM.ID_TEMPO = T.ID_TEMPO
WHERE C.SALDO >= '10000'
AND TT.DESCRICAO = 'PIX'
AND CAL.DATA_TRANSACAO > '5000'
AND TEM.MES = GETDATE() 
----------------------------------------------------------
2.1 CONSULTA 
SELECT C.NOME AS CLIENTE,
       DATEPART(YEAR,CAL.DATA_TRANSACAO) AS ANO,
       DATEPART(MONTH,CAL.DATA_TRANSACAO) AS MES, 
       AVG(FS.SALDO) AS SALDO_MEDIO,
       COUNT(T.ID_FATO_TRANSACAO) AS QTD_TRANSACOES_PIX,
       SUM(T.VALOR_TRANSACAO) AS VALOR_TOTAL_PIX
FROM FATO_SALDO FS 
JOIN DIM_CLIENTE C
ON FS.ID_CLIENTE = C.ID_CLIENTE 
JOIN FATO_TRANSACAO T 
ON FS.ID_CLIENTE = T.ID_CLIENTE 
JOIN DIM_CALENDARIO CAL 
ON T.ID_TEMPO = CAL.ID_TEMPO 
WHERE T.TIPO_TRANSACAO = 'PIX'
AND T.VALOR_TRANSACAO >= 5000 
GROUP BY  C.NOME, DATEPART(YEAR,CAL.DATA_TRANSACAO),DATEPART(MONTH,CAL.DATA_TRANSACAO)
HAVING AVG(FS.SALDO) > 10000
AND COUNT(T.ID_FATO_TRANSACAO) > 10 
ORDER BY SALDO_MEDIO DESC;
-----------------------------------------------------------------------------
--historico consulta 
SELECT  C.NOME AS CLIENTE,
        C.SEGMENTO,
        G.NOME_GERENTE,
        A.NOME_AGENCIA, 
        C.CLASS_RISCO ,
        T.TIPO_TRANSACAO,
        CAL.DATA_TRANSACAO
FROM FATO_TRANSACAO T 
JOIN DIM_CLIENTE C
ON T.ID_CLIENTE = C.ID_CLIENTE 
JOIN DIM_CALENDARIO CAL
ON T.ID_TEMPO = CAL.ID_TEMPO 
JOIN BRIGDE_CLIENTE_GERENTE BG 
ON C.ID_CLIENTE = BG.ID_CLIENTE 
JOIN DIM_GERENTE G 
ON BG.ID_GERENTE  = G.ID_GERENTE 
JOIN DIM_AGENCIA A 
ON G.ID_AGENCIA = A.ID_AGENCIA
WHERE BG.DATA_INICIO BETWEEN BG.DATA_FIM
------------------------------------------------------------------
---28 GRUPO ECONOMICO 
CREATE TABLE DIM_GRUPO_ECONOMICO (
        ID_GRUPO INT IDENTITY(1,1) PRIMARY KEY,
        NOME_GRUPO VARCHAR(100),
        SETOR VARCHAR(100),
        DESCRICAO VARCHAR(100)
)

CREATE TABLE BRIGDE_CLIENTE_GRUPO_ECONOMICO(
        ID_CLIENTE INT,
        ID_GRUPO INT,
        DATA_INICIO,
        DATA_FIM,
        PRIMARY KEY(ID_CLIENTE,ID_GRUPO),
        FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
        FOREIGN KEY (ID_GRUPO) REFERENCES DIM_GRUPO_ECONOMICO(ID_GRUPO),
)
----------------------------------------------------------------------------
