1 - consulta 

SELECT TOP 20,
        C.NOME AS CLIENTE,
        C.SEGMENTO,
        COUNT(T.VALOR_TRANSACAO) AS QTD_TRANSACOES,
        SUM(T.VALOR_TRANSACAO) AS VALOR_TOTAL,
        AVG(T.VALOR_TRANSACAO) AS TICKET_MEDIO
FROM FATO_TRANSACAO T 
JOIN DIM_CLIENTE C 
ON T.ID_CLIENTE = C.ID_CLIENTE
JOIN DIM_TEMPO TT 
ON T.ID_TEMPO_TRANSACAO = TT.ID_TEMPO
WHERE T.DATA >= DATEADD(DAY,-90,GETDATE())
GROUP BY C.NOME,C.SEGMENTO
ORDER BY VALOR_TOTAL DESC;

2- CONSULTA 

SELECT C.NOME AS CLIENTE,
AVG(C.SALDO) AS SALDO_MEDIO
FROM FATO_TRANSACAO T
JOIN DIM_CLIENTE C
ON T.ID_CLIENTE = C.ID_CLIENTE
JOIN DIM_TIPO_TRANSACAO TT 
ON T.ID_TIPO_TRANSACAO = TT.ID_TIPO_TRANSACAO
JOIN CAL.DIM_TEMPO  TEM
ON T.ID_TEMPO_TRANSACAO = TT.ID_TEMPO
JOIN DIM_TEMPO TEM 
ON TEM.ID_TEMPO = T.ID_TEMPO
WHERE C.SALDO >= '10000'
AND TT.DESCRICAO = 'PIX'
AND TEM.DATA> '5000'
AND TEM.MES = GETDATE() 
----------------------------------------------------------
-- MEDIA CLIENTE ANO/MES
WITH SALDO_CONSOLIDADO(
        SELECT FS.ID_CLIENTE,
                DATEPART(YEAR FROM FS.DATA_SALDO) AS ANO,
                DATEPART(MONTH FROM FS.DATA_SALDO) AS MES,
                AVG(FS.SALDO) AS SALDO_MEDIO,
        FROM FATO_SALDO FS 
        GROUP BY   FS.ID_CLIENTE,DATEPART(YEAR FROM FS.DATA_SALDO), DATEPART(MONTH FROM FS.DATA_SALDO),        
)

-- calculo de pix por ANO/MES
WITH PIX_CONSOLIDADO(
        SELECT T.ID_CLIENTE,
               DATEPART(YEAR,CAL.DATA_TRANSACAO) AS ANO,
               DATEPART(MONTH,CAL.DATA_TRANSACAO) AS MES,
               COUNT(T.ID_FATO_TRANSACAO) AS QTD_TRANSACOES_PIX,
               SUM(T.VALOR_TRANSACAO) AS VALOR_TOTAL_PIX   
        FROM FATO_TRANSACAO T
        JOIN DIM_TEMPO TT
        ON T.ID_TEMPO_TRANSACAO = TT.ID_TEMPO
        GROUP BY  T.ID_CLIENTE,DATEPART(YEAR,TT.DATA),DATEPART(MONTH,TT.DATA)
)
2.1 CONSULTA
-- unificando os ctes para chegar na resposta de quantidade de transações via pix
SELECT C.NOME AS CLIENTE,
       S.ANO,
       S.MES,
       S.SALDO_MEDIO,
       P.QTD_TRANSACOES_PIX,
       P.VALOR_TOTAL_PIX 
FROM SALDO_CONSOLIDADO S 
JOIN PIX_CONSOLIDADO P
ON S.ID_CLIENTE = P.ID_CLIENTE
   AND S.ANO = P.ANO
   AND S.MES = P.MES
JOIN DIM_CLIENTE C
ON S.ID_CLIENTE = C.ID_CLIENTE 
WHERE S.SALDO_MEDIO > 10000
AND T.TIPO_TRANSACAO = 'PIX'
AND P.QTD_TRANSACOES_PIX >= 10 
ORDER BY SALDO_MEDIO DESC;
-----------------------------------------------------------------------------
--historico consulta 
SELECT  C.NOME AS CLIENTE,
        C.SEGMENTO,
        G.NOME_GERENTE,
        A.NOME_AGENCIA, 
        C.CLASS_RISCO ,
        T.TIPO_TRANSACAO,
        CAL.DATA_TRANSACAO
FROM FATO_TRANSACAO T 
JOIN DIM_CLIENTE C
ON T.ID_CLIENTE = C.ID_CLIENTE 
JOIN DIM_TEMPO TT
ON T.ID_TEMPO_TRANSACAO = TT.ID_TEMPO 
JOIN BRIGDE_CLIENTE_GERENTE BG 
ON C.ID_CLIENTE = BG.ID_CLIENTE 
JOIN DIM_GERENTE G 
ON BG.ID_GERENTE  = G.ID_GERENTE 
JOIN DIM_AGENCIA A 
ON G.ID_AGENCIA = A.ID_AGENCIA
WHERE TT.DATA BETWEEN BG.DATA_INICIO AND COALESCE(BG.DATA_FIM,'3000-12-31')
------------------------------------------------------------------
---28 GRUPO ECONOMICO 
CREATE TABLE DIM_GRUPO_ECONOMICO (
        ID_GRUPO INT IDENTITY(1,1) PRIMARY KEY,
        NOME_GRUPO VARCHAR(100),
        SETOR VARCHAR(100),
        DESCRICAO VARCHAR(100)
)

CREATE TABLE BRIGDE_CLIENTE_GRUPO_ECONOMICO(
        ID_CLIENTE INT,
        ID_GRUPO INT,
        DATA_INICIO,
        DATA_FIM,
        PRIMARY KEY(ID_CLIENTE,ID_GRUPO),
        FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
        FOREIGN KEY (ID_GRUPO) REFERENCES DIM_GRUPO_ECONOMICO(ID_GRUPO),
)
----------------------------------------------------------------------------
