     CONSTRAINT FK_DIM_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES DIM_CLIENTE(ID_CLIENTE),
     CONSTRAINT FK_DIM_CONTA FOREIGN KEY (ID_CONTA) REFERENCES DIM_CONTA(ID_CONTA),
     CONSTRAINT FK_DIM_CANAL FOREIGN KEY (ID_CANAL) REFERENCES DIM_CANAL(ID_CANAL),
     CONSTRAINT FK_DIM_CALENDARIO FOREIGN KEY (ID_CALENDARIO) REFERENCES DIM_CALENDARIO(ID_CALENDARIO),
     CONSTRAINT FK_DIM_TIPO_TRANSACAO --FOREIGN KEY (ID_TIPO_TRANSACAO) REFERENCES DIM_TIPO_TRANSACAO(ID_TIPO_TRANSACAO),
     CONSTRAINT FK_DIM_LOCALIZACAO FOREIGN KEY (ID_LOCALIZACAO) REFERENCES DIM_LOCALIZACAO(ID_LOCALIZACAO),
     CONSTRAINT FK_DIM_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO(ID_TEMPO),
     CONSTRAINT FK_DIM_CREDITO FOREIGN KEY (ID_CREDITO) REFERENCES DIM_CREDITO(ID_CREDITO),
     CONSTRAINT FK_DIM_GERENTE FOREIGN KEY (ID_GERENTE) REFERENCES DIM_GERENTE(ID_GERENTE),

    CONSTRAINT FK_DIM_CAMPANHA FOREIGN KEY (ID_CAMPANHA) REFERENCES DIM_CLIENTE(ID_CAMPANHA),

